Repository selsa-inube/inubekit-select, pull requests merged in 2024-08, with the labels that each got.

#18 Remove Unnecessary Prop from Component as per Figma Design
  src/Select/index.tsx
  src/Select/interface.tsx
  src/Select/stories/Select.stories.tsx
  src/Select/styles.js
Labels: minor

#19 Update Foundations Dependency
  package.json
  src/Select/OptionItem/styles.js
  src/Select/stories/Select.inForm.stories.tsx
  src/Select/styles.js
Labels: minor, dependencies

#20 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#21 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#22 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#23 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#24 Update stack dependency to latest version
  package.json
Labels: minor, dependencies

#25 Update text dependency to latest version
  package.json
Labels: minor, dependencies

#26 Extend `<Select />` Component to Allow Clearing of Selected
  src/Select/index.tsx
  src/Select/interface.tsx
  src/Select/styles.js
Labels: minor

#28 Fcanas/refactor value prop on change
  src/Select/OptionItem/index.tsx
  src/Select/OptionList/OptionList.stories.tsx
  src/Select/OptionList/index.tsx
  src/Select/index.tsx
  src/Select/interface.tsx
  src/Select/props.ts
  src/Select/stories/Select.form.Controller.tsx
  src/Select/stories/Select.inForm.stories.tsx
  src/Select/stories/Select.stories.tsx
  src/Select/stories/SelectController.tsx
  src/Select/styles.js
  src/index.ts
Labels: major

#29 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#30 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#31 Update text dependency to latest version
  package.json
Labels: minor, dependencies

#32 Refactor onClick Handler to Prevent Error Throwing
  src/Select/index.tsx
  src/Select/stories/Select.form.Controller.tsx
  src/Select/stories/SelectController.tsx
Labels: minor

#33 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#34 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#35 Update stack dependency to latest version
  package.json
Labels: minor, dependencies

#36 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#37 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#38 Update stack dependency to latest version
  package.json
Labels: minor, dependencies

#39 Update text dependency to latest version
  package.json
Labels: minor, dependencies

#40 Update OptionItem to Change Background Color on Hover
  src/Select/OptionItem/index.tsx
  src/Select/OptionItem/styles.js
  src/Select/OptionList/styles.js
  src/Select/interface.tsx
Labels: minor

#41 Add `readOnly` Prop to Control Typing in Inner TextField
  src/Select/OptionList/index.tsx
  src/Select/OptionList/styles.js
  src/Select/index.tsx
  src/Select/interface.tsx
  src/Select/props.ts
  src/Select/stories/Select.stories.tsx
Labels: enhancement, minor

#42 Update Documentation in `props.ts`
  src/Select/OptionItem/props.ts
  src/Select/OptionList/props.tsx
  src/Select/props.ts
Labels: documentation

#43 Update text dependency to latest version
  package.json
Labels: minor, dependencies

#44 Update `<Select />` to Prevent Errors Related to DOM and Props
  src/Select/OptionList/index.tsx
  src/Select/OptionList/styles.js
Labels: minor

#45 Adjust behavior in order to allow write according to readonly
  src/Select/index.tsx
  src/Select/interface.tsx
  src/Select/stories/Select.stories.tsx
Labels: minor

#46 Add Filtering Behavior Through Props
  src/Select/OptionList/OptionList.stories.tsx
  src/Select/OptionList/index.tsx
  src/Select/index.tsx
  src/Select/interface.tsx
  src/Select/stories/Select.filter.stories.tsx
  src/Select/stories/SelectControllerFilter.tsx
Labels: minor

#47 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#48 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#49 Update stack dependency to latest version
  package.json
Labels: minor, dependencies

#50 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#52 Update text dependency to latest version
  package.json
Labels: minor, dependencies
